import { useState } from "react";
import { useStory } from "@/lib/story-context";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Check, Edit2, Share2, ArrowRight, Upload } from "lucide-react";
import { motion } from "framer-motion";
import { useToast } from "@/hooks/use-toast";

export default function Review() {
  const { generatedStory, studentName, setGeneratedStory, storyId } = useStory();
  const [isEditing, setIsEditing] = useState(false);
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const [isPublishing, setIsPublishing] = useState(false);

  const handleSaveEdit = async () => {
    if (!storyId) return;
    
    try {
      const response = await fetch(`/api/stories/${storyId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content: generatedStory }),
      });

      if (!response.ok) throw new Error("Failed to update story");

      toast({
        title: "Saved",
        description: "Your changes have been saved.",
      });
      setIsEditing(false);
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to save changes. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handlePublish = async () => {
    if (!storyId) return;
    
    setIsPublishing(true);
    try {
      const response = await fetch(`/api/stories/${storyId}/publish`, {
        method: "POST",
      });

      if (!response.ok) throw new Error("Failed to publish story");

      toast({
        title: "Story Published!",
        description: "Your story has been submitted successfully.",
      });
      setLocation("/success");
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to publish story. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsPublishing(false);
    }
  };

  return (
    <div className="min-h-screen bg-muted/30 py-8 px-4 md:py-12">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8 text-center space-y-2">
          <h1 className="text-3xl font-serif font-bold text-foreground">Your Story is Ready</h1>
          <p className="text-muted-foreground">Review, edit, and approve your story below.</p>
        </div>

        <div className="grid md:grid-cols-[1.5fr,1fr] gap-8">
          {/* Story Card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <Card className="overflow-hidden border-none shadow-xl bg-white">
              <div className="bg-primary h-2 w-full" />
              <div className="p-8 md:p-10 space-y-6">
                <div className="flex items-center justify-between">
                  <h2 className="text-2xl font-serif font-bold text-foreground">
                    {studentName ? `${studentName}'s Journey` : "Student Story"}
                  </h2>
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    onClick={() => {
                      if (isEditing) {
                        handleSaveEdit();
                      } else {
                        setIsEditing(true);
                      }
                    }}
                    className="text-primary hover:text-primary/80 hover:bg-primary/5"
                  >
                    {isEditing ? <Check className="h-4 w-4 mr-2" /> : <Edit2 className="h-4 w-4 mr-2" />}
                    {isEditing ? "Save Changes" : "Edit Text"}
                  </Button>
                </div>

                {isEditing ? (
                  <Textarea 
                    value={generatedStory} 
                    onChange={(e) => setGeneratedStory(e.target.value)}
                    className="min-h-[300px] font-serif text-lg leading-relaxed border-primary/20 focus:border-primary"
                  />
                ) : (
                  <div className="prose prose-lg text-foreground/80 font-serif leading-loose">
                    {generatedStory.split('\n').map((paragraph, i) => (
                      <p key={i}>{paragraph}</p>
                    ))}
                  </div>
                )}

                <div className="pt-6 border-t flex flex-col sm:flex-row gap-4 justify-between items-center">
                    <p className="text-sm text-muted-foreground italic">
                        Generated by StoryCollector AI
                    </p>
                    <div className="flex gap-2">
                        {/* Placeholder for photo upload */}
                        <Button variant="outline" className="gap-2" onClick={() => {
                            toast({
                                title: "Photo Upload",
                                description: "This feature is currently a mockup. In the final version, this will open a file picker.",
                            });
                        }}>
                            <Upload className="h-4 w-4" />
                            Add Photo
                        </Button>
                    </div>
                </div>
              </div>
            </Card>
          </motion.div>

          {/* Sidebar Actions */}
          <motion.div
             initial={{ opacity: 0, x: 20 }}
             animate={{ opacity: 1, x: 0 }}
             transition={{ duration: 0.5, delay: 0.2 }}
             className="space-y-6"
          >
            <Card className="p-6 space-y-4 shadow-md border-muted">
                <h3 className="font-semibold text-lg">Next Steps</h3>
                <ul className="space-y-3">
                    <li className="flex gap-3 text-sm text-muted-foreground">
                        <div className="w-6 h-6 rounded-full bg-green-100 text-green-600 flex items-center justify-center shrink-0">
                            <Check className="h-3 w-3" />
                        </div>
                        <span>Story drafted</span>
                    </li>
                    <li className="flex gap-3 text-sm text-muted-foreground">
                        <div className="w-6 h-6 rounded-full bg-primary/10 text-primary flex items-center justify-center shrink-0">
                            2
                        </div>
                        <span>Review and approve content</span>
                    </li>
                    <li className="flex gap-3 text-sm text-muted-foreground">
                        <div className="w-6 h-6 rounded-full bg-muted text-muted-foreground flex items-center justify-center shrink-0">
                            3
                        </div>
                        <span>Published to Student Success Catalog</span>
                    </li>
                </ul>
                
                <div className="pt-4 space-y-3">
                    <Button 
                      onClick={handlePublish} 
                      disabled={isPublishing}
                      className="w-full h-12 text-lg shadow-lg bg-primary hover:bg-primary/90"
                    >
                        {isPublishing ? "Publishing..." : "Approve & Publish"}
                        {!isPublishing && <ArrowRight className="ml-2 h-5 w-5" />}
                    </Button>
                    <p className="text-xs text-center text-muted-foreground">
                        By publishing, you agree to our Terms of Service.
                    </p>
                </div>
            </Card>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
